package com.example.backend.parallel;

import java.util.List;

import com.example.backend.dataset.DatasetLoader;
import com.example.backend.dataset.DatasetUtils;

public class MainApp {

    public static void main(String[] args) throws Exception {

        // 1. Load dataset (generated by your friend)
        double[][] rawData = DatasetLoader.loadCSV("dataset_100000points_5D_K5.csv");

        // 2. Normalize (VERY IMPORTANT)
        DatasetUtils.normalize(rawData);

        // 3. Convert to Point objects
        List<Point> points = KMeansUtils.convertToPoints(rawData);

        int k = 5;
        int maxIterations = 10;
        int numThreads = Runtime.getRuntime().availableProcessors();

        System.out.println("Running Parallel K-Means...");
        System.out.println("Threads: " + numThreads);

        long start = System.currentTimeMillis();

        KMeansParallel.runKMeans(points, k, maxIterations, numThreads);

        long end = System.currentTimeMillis();

        System.out.println("Execution Time: " + (end - start) + " ms");
    }
}